import { Tiro_Bangla } from "next/font/google";
import "./globals.css";
import MainApp from "./MainApp";

const tiroBangla = Tiro_Bangla({
  weight: ["400"],
  style: ["normal"],
  subsets: ["bengali"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tiroBangla.className} max-w-[700px] m-auto box-border bg-gray-100`}>
        <div className="w-full relative overflow-x-hidden bg-[#03989e] min-h-screen  text-gray-950 pb-4">
        <MainApp>{children}</MainApp>
        </div>
      </body>
    </html>
  );
}
